### ISSUE TITLE
Can't use for server-side rendering

### ISSUE THREAD

**Issue by chielkunkels** [cloudflare/react-gateway#1]
I just stumbled across this package while looking at `react-modal2` (while researching an alternative for `react-modal` and I really like the philosophy of creating small, dumb components that do one thing.

However, I'm working on an isomorphic app and this package currently can't be used server-side, since it dies on this error:

```
./node_modules/react-gateway/index.js:20
      to: document.body
          ^

ReferenceError: document is not defined
    at Function.module.exports.React.createClass.getDefaultProps (./node_modules/react-gateway/index.js:20:11)
```

This is pretty logical of course, but it would be excellent if this package could be used server-side too so it can be used in isomorphic apps.

**Comment by brabeji** [comment]
I needed fix asap so my fork is here https://github.com/brabeji/react-gateway/tree/server-renderable , I could submit PR when I'm able to fix tests.

**Comment by chielkunkels** [comment]
@brabeji out of curiosity, how do you use this on serverside? check if `document` is defined, and if not, don't pass anything?

**Comment by brabeji** [comment]
Didn't get his far yet :)) On a second thought, I will maybe omit react-gateway and render modals in proper location in the first place.

**Comment by thejameskyle** [comment]
I was experimenting with a way to render a container element that gateway can use, but didn't get it working.

```js
function Application() {
  return (
    <div>
      <div>
        <ReactGateway to="global">
          ...
        </ReactGateway>
      </div>
      
      <ReactGateway.Dest name="global"/>
    </div>
  );
}
```

**Comment by chielkunkels** [comment]
I'm happy to work on a pull request for this if I roughly know what to do
or where to start looking. I know more or less how react's rendering
process works but not really in detail.

I'm just wondering how you'd work this out serverside. Using that unsafe
subtree render, I guess you'd want to render multiple trees, potentially,
and then dump them into the body of yiur output. Question is how would the
client side code react to this...

Looking forward to your insights!

**Comment by thejameskyle** [comment]
This is the basic idea: http://jsbin.com/xebizav/edit?js,output

I'll try putting something together tonight

**Comment by chielkunkels** [comment]
Ah, so you'd create one child for all used gateways, and then render that one into the server response alongside the rest of your app? Will react "understand" this and simply re-use the markup, or?

**Comment by thejameskyle** [comment]
[I have it working already](https://twitter.com/thejameskyle/status/677397967540654080), React doesn't throw any warnings so I think it works fine. I'm testing a bunch of different scenarios now and making sure I'm not creating any memory leaks, but I think this is the right solution.

**Comment by chielkunkels** [comment]
Oh that is awesome! So from what I'm seeing here, you'll need to render the GatewayProvider alongside your App inside a root element so that you can then use it, not being dependent on document body?

That's a really elegant solution, very nice!

**Comment by thejameskyle** [comment]
The only reason for the `<GatewayProvider>` is to instantiate a `registry` that gets passed in through `childContext`. I'm trying to understand the implications of that fully as I've never used context before.

**Comment by chielkunkels** [comment]
I think this is also the cleanest way to handle this though, since you don't have to do any weird/disgusting workarounds server-side, and you can use the same logic on both client and server.

Any idea of when you'll be releasing this? I'd really prefer to use this rather than `react-modal` or `react-portal` which do a lot more than I'd like.

**Comment by thejameskyle** [comment]
I'm trying to finish it tonight to open a PR, but it'll probably take me a day or two before releasing it.

**Comment by chielkunkels** [comment]
D'awh okay. That's too bad. Looking forward to the release! :+1:

**Comment by thejameskyle** [comment]
Ugh, so I just discovered `context` doesn't work in between components.

So you couldn't do:

```js
function HomePage() {
  return (
    <div>
      <Gateway into="global">...</Gateway>
      <GatewayDest name="global"/>
    </div>
  );
}

function Application() {
  return (
    <GatewayProvider>
      <Application/>
    </GatewayProvider>
  );
}
```

I need to figure out a better way of doing this.

**Comment by chielkunkels** [comment]
I'm sure that's just pseudo code, but you can't render `<Application />` in its own render function I would imagine?

If you have something like this:

```
function App() {
    return (
        <Gateway into="global">
            <p>I'm on a boat, err gateway</p>
        </Gateway>
    );
}

function Root() {
    return (
        <GatewayProvider>
            <App />
            <GatewayDest name="global" />
        </GatewayProvider>
    );
}
```

`GatewayProvider` would provide the context, and everything in its subtree should be able to access said context. Do you have some code somewhere in a branch or something that I can look at?

**Comment by chielkunkels** [comment]
I'm just throwing something together in a jsbin, will update shortly.

**Comment by chielkunkels** [comment]
I think I'm almost there: http://jsbin.com/qavule/1/edit?js,output

Problem I'm facing now is that the `GatewayDest` has not yet registered itself when it needs to be rendered into. Wondering if stuffing it inside of another lifecycle hook would help, so it can register itself in the context before the App uses it.

Thoughts?

**Comment by chielkunkels** [comment]
Alright, I've made a little more progress: http://jsbin.com/qavule/2/edit?js,output

Now, upon mounting the `GatewayDest` a ref is saved to the div, and then that is registered into `this.context.gateways` with the given name.

The problem now is that the `GatewayDest` needs to be defined before it is used as a `Gateway`'s `into`. I'm not really sure if there's any obvious way around this, but I don't see it.

I don't really know if it really matters too much if the `GatewayDest`s are above the application, but it seems a bit limiting and error-prone.

Also, I'm curious if this is actually what you were doing in your stuff or that I'm on a completely wrong path, haha.

**Comment by thejameskyle** [comment]
Both the `<Gateway>` and the `<GatewayDest>` need to be able to grab the context from `<GatewayProvider>` but the way React is designed is to only pass context within the same component which is not a limitation that will be okay for this library

**Comment by thejameskyle** [comment]
The only alternative here is to have a singleton in the library, I'm afraid of doing that and opening up memory leaks

**Comment by chielkunkels** [comment]
Yeah for sure, I agree. But the question is, is there any way around this
in the current solution I have?

**Comment by thejameskyle** [comment]
What you have is extremely similar to what I created which doesn't work

**Comment by chielkunkels** [comment]
Haha okay. That's too bad really, it feels like the only thing that's
lacking in this solution is that the dests need to be defined before they
are used.

Do you have any other ideas?

**Comment by thejameskyle** [comment]
Never mind, I was just being dumb. I've pushed new changes. I will write tests tomorrow (seeing star wars tonight) and new docs and publish.

**Comment by chielkunkels** [comment]
Ah! I was supposed to see star wars yesterday evening but had a christmas
party from my new work. Enjoy!

Gonna have a look at the code when I get to work. :)

**Comment by chielkunkels** [comment]
The code looks great - you did a really nice job man. The only thing I don't quite understand is why it works for you, defining the gateways later, but I guess it's cause you use the registry as a middleman and don't directly refer to the gateways.

Awesome job, thanks for picking this up so fast, helps me out a ton.

**Comment by thejameskyle** [comment]
`react-gateway@2` and `react-modal2@3` have been published

**Comment by chielkunkels** [comment]
Awesome! Thanks again for your hard work mate. :)
