### ISSUE TITLE
Invalid context `gatewayRegistry` of type `GatewayRegistry` supplied to `Gateway`

### ISSUE THREAD

**Issue by chielkunkels** [cloudflare/react-gateway#20]
I've recently started getting this issue, and I really don't know where it's coming from. The full message is:

```
Warning: Failed context type: Invalid context `gatewayRegistry` of type `GatewayRegistry` supplied to `Gateway`, expected instance of `GatewayRegistry`.
```

I'm not really sure where this comes from since I've been using this library for a while and this is the first time I come across it. I'll try digging into the Gateway component to see what's going on.

**Comment by chielkunkels** [comment]
Looks like this is actually a problem on my end with multiple copies of react-gateway... Sorry to waste your time reading this.

**Comment by chardskarth** [comment]
I hope you could help me with this. How exactly did you have multiple copies of react-gateway?
